# Site settings
email: admin@rotaract3190.org
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Rotaract 3190 | Blog
description: Take a Step Towards change!!!
url: "https://blog.rotaract3190.org"
twitter_username: 
default_img: 

# Profile settings
name: Rotaract 3190
profile_img: 
profile: Let us Take a Step Towards change!!!
social:
  phone: tel:8553788515
  facebook: https://www.facebook.com/RIDist3190/
  instagram: https://www.instagram.com/rotaract3190/
  github: https://github.com/Rotaract3190/
  rss: https://blog.rotaract3190.org/feed.xml/
  

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
