backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  squash_merges: true

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "assets/img" # Folder where user uploaded files should go
site_url: https://blog.rotaract3190.org
display_url: https://blog.rotaract3190.org
# logo_url: https://blog.rotaract3190.org/assets/img/favicon.png


collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime"} # {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Twitter Text", name: "twitter_text", widget: "markdown"}
      - {label: "Introduction", name: "introduction", widget: "markdown"}
      - {label: "Image", name: "image", widget: "string", default: "/assets/img/_____"}
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - { label: "Facts", value: "Facts" }
          - { label: "Humans of 3190", value: "Humans of 3190" }
          - { label: "Wildlife", value: "Wildlife" }
          - { label: "Zonal Event", value: "Zonal Event" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        default: ["Tag1, Tag2"]
      - label: Author
        name: author
        widget: object
        fields:
          - {label: "Author Name", name: "name", widget: "string", tagname: "name"}
          - {label: "Author Profile", name: "profile", widget: "markdown"}
          - {label: "Author Image", name: "image", widget: "string", default: "/assets/img/authors/_____"}
          - label: Social
            name: social
            widget: object
            fields:
              - {label: "Author Instagram", name: "instagram", widget: "string", default: ""}
              - {label: "Author Facebook", name: "facebook", widget: "string", default: ""}
              - {label: "Author Github", name: "github", widget: "string", default: ""}
              - {label: "Author Twitter", name: "twitter", widget: "string", default: ""}
              - {label: "Author Medium", name: "medium", widget: "string", default: ""}
              - {label: "Author Linkedin", name: "linkedin", widget: "string", default: ""}
              - {label: "Author Website", name: "website", widget: "string", default: ""}
      - {label: "Body", name: "body", widget: "markdown"} 