backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "assets/img" # Folder where user uploaded files should go

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "string", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - label: "Categories"
        name: "categories"
        widget: "list"
        allow_add: true
        default: ["Option1,Option2"]
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "string", tagname: "h2"}
      - {label: "Image-sm", name: "image-sm", widget: "string", tagname: "h2"}
      - {label: "Body", name: "body", widget: "markdown"}
